harp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from pedal_settings import views
from django.utils.translation import ugettext_lazy as _


handler404 = views.error404
handler500 = views.error500


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'harp.views.dashboard', name='dashboard'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.home, name='home'),
    url(_(r'^about/$'), views.about, name='about'),
    url(_(r'^dashboard/$'), views.dashboard, name='dashboard'),
    url(_(r'^dashboard/all/$'), views.show_all_settings, name='show_all_settings'),
    url(r'^dashboard/download/$', views.download_all_settings, name='download_all_settings'),
    url(_(r'^dashboard/index$'), views.get_by_index, name='get_by_index'),
    url(_(r'^dashboard/prime$'), views.get_by_prime, name='get_by_prime'),
    url(_(r'^dashboard/accidents$'), views.get_by_accidents, name='get_by_accidents'),
    url(_(r'^dashboard/index/(?P<pedal_index>\d+)/$'), views.show_settings_by_index, name='show_settings_by_number'),
    url(_(r'^dashboard/prime/(?P<pedal_prime>\w+)/$'), views.show_settings_by_prime, name='show_settings_by_prime'),
    url(_(r'^dashboard/accidents/(?P<accidents>\w+)/$'), views.show_settings_by_accidents, name='show_settings_by_accidents'),
    url(_(r'^dashboard/statistics/$'), views.show_statistics, name='show_statistics'),
    url(r'^admin/$', include(admin.site.urls)),
)

pedal_settings/models.py
from django.db import models

# Create your models here.

pedal_settings/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _

def validate_number(value):
    if value not in map(str, range(0, 2222222)):
        raise ValidationError(_(u'%s is not a number in base 3 between 0 and 2222222') % value)


def validate_prime(seq):
    allowed = list(map(str, range(10)))
    for s in ('a', 'b'):
        allowed.append(s)
        allowed.append(s.upper())

    if not all((v in allowed) for v in seq):
        raise ValidationError(_(u'%s is not in prime form format') % seq)


class IndexForm(forms.Form):
    settings_index = forms.CharField(label=_('Settings index'),
                                     max_length=7,
                                     help_text=_('Insert an index number in base 3 between 0 and 2222222, such as 20102'),
                                     validators=[
                                         RegexValidator(
                                             r'^[012]*$',
                                             _(u'Only 0-2 are allowed.'),
                                             _(u'Invalid Number')
                                         ),
                                         validate_number,
                                     ])


class PrimeForm(forms.Form):
    settings_prime = forms.CharField(label=_('Settings Prime Form'),
                                        min_length=4,
                                        max_length=12,
                                        help_text=_('Insert a pcset prime form such as 02468A'),
                                        validators=[validate_prime])

class AccidentsForm(forms.Form):
    choices = ((0, 'b'), (1, 'n'), (2, '#'))
    c = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'form-inline'}), choices=choices)
    d = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'form-inline'}), choices=choices)
    e = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'form-inline'}), choices=choices)
    f = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'form-inline'}), choices=choices)
    g = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'form-inline'}), choices=choices)
    a = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'form-inline'}), choices=choices)
    b = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'form-inline'}), choices=choices)

pedal_settings/views.py
from io import BytesIO
import zipfile

import pandas
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.utils.translation import get_language
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

from pedal_settings.forms import IndexForm, PrimeForm, AccidentsForm
from lib import core
from pedal_settings.templatetags.dispositions_extras import radial_format, scalar_format


# Create your views here.

COLUMNS = ['Notes (scalar)', 'Notes (radial)', 'PC Set', 'Prime Form', 'Forte class']
RADIAL = False


def get_language_url():
    # ugly javascript localization
    if get_language() == 'pt-br':
        return "http://cdn.datatables.net/plug-ins/3cfcc339e89/i18n/Portuguese-Brasil.json"
    else:
        return "http://cdn.datatables.net/plug-ins/3cfcc339e89/i18n/English.json"


def error404(request):
    return render(request, "404.html")


def error500(request):
    return render(request, "500.html")


def home(request):
    return render(request, "index.html")


def dashboard(request):
    return render(request, "dashboard.html")


def about(request):
    return render(request, "about.html")


def show_settings_by_index(request, pedal_index):
    df = core.load_csv()

    series = df.loc[int(pedal_index)]
    df = pandas.DataFrame([series])

    args = {
        'title': 'Settings index {}'.format(pedal_index),
        'df': df,
        'language_url': get_language_url(),
        'radial': RADIAL,
    }
    return render(request, "show_settings.html", args)


def show_settings_by_prime(request, pedal_prime):
    df = core.load_csv()

    df = df[df['Prime Form'] == pedal_prime]

    args = {
        'title': 'Settings with PC Prime Form {}'.format(pedal_prime),
        'settings': len(df),
        'df': df,
        'language_url': get_language_url(),
        'radial': RADIAL,
    }
    return render(request, "show_settings.html", args)


def show_settings_by_accidents(request, accidents):
    df = core.load_csv()

    df = df[df['Accidents'] == accidents]

    args = {
        'title': 'Settings with PC Prime Form {}'.format(accidents),
        'settings': len(df),
        'df': df,
        'language_url': get_language_url(),
        'radial': RADIAL,
    }
    return render(request, "show_settings.html", args)


def show_all_settings(request):
    df = core.load_csv()

    args = {
        'title': 'All settings',
        'settings': len(df),
        'df': df,
        'language_url': get_language_url(),
        'radial': RADIAL,
    }
    return render(request, 'show_settings.html', args)


def get_by_index(request):
    if request.method == 'POST':
        form = IndexForm(request.POST)
        if form.is_valid():
            ind = form.cleaned_data['settings_index']
            return HttpResponseRedirect(reverse('pedal_settings.views.show_settings_by_index', args={ind, }))

    else:
        form = IndexForm()
    return render(request, 'filter_index.html', {'form': form})


def get_by_prime(request):
    if request.method == 'POST':
        form = PrimeForm(request.POST)
        if form.is_valid():
            prime = form.cleaned_data['settings_prime']
            return HttpResponseRedirect(reverse('pedal_settings.views.show_settings_by_prime', args={prime, }))

    else:
        form = PrimeForm()
    return render(request, 'filter_prime_form.html', {'form': form})


def get_by_accidents(request):
    if RADIAL:
        notes = list('dcbefga')
    else:
        notes = list('cdefgab')
    if request.method == 'POST':
        form = AccidentsForm(request.POST)
        if form.is_valid():
            accidents = tuple([int(form.cleaned_data[c]) for c in notes])
            df = core.load_csv()
            disposition = df[df['Accidents'] == str(accidents)]
            index = disposition.index.values[0]
            return HttpResponseRedirect(reverse('pedal_settings.views.show_settings_by_index', args={index, }))

    else:
        init_dic = {}
        for a in list('abcdefg'):
            init_dic[a] = 0
        form = AccidentsForm(init_dic)
    return render(request, 'filter_accidents.html', {'form': form})


def download_all_settings(request):
    df = core.load_csv()
    buff = BytesIO()

    df = df[COLUMNS]

    df.index = [scalar_format(i) for i in df.index]
    df.index.name = 'Index'

    zip_archive = zipfile.ZipFile(buff, mode='w')
    zip_archive.writestr('pedal_settings.txt', df.to_string())
    zip_archive.close()

    response = HttpResponse(buff.getvalue(), content_type="application/x-zip-compressed")
    response['Content-Disposition'] = 'attachment; filename=pedal_settings.zip'
    return response


def show_statistics(request):
    df = core.load_csv()
    pf_series = df['Prime Form']

    type_series = pandas.Series(map(len, pf_series), index=pf_series.index)
    type_count_simple = type_series.value_counts(sort=True)
    type_count_normalized = type_series.value_counts(normalize=True, sort=True)
    type_count_df = pandas.DataFrame([type_count_simple, type_count_normalized]).T
    type_count_df.columns = [_('Amount'), _('Proportion')]
    type_count_df.index.name = _('Number of Pitch Classes')
    type_count_df = type_count_df.T

    count_items = type_count_df.T[_('Amount')].to_dict().items()
    chord_type_pie_data = list(map(lambda x: [str(x[0]), x[1]], count_items))
    chord_type_pie_data.insert(0, list(type_count_df.index))

    pf_histogram_data = pf_series.value_counts().to_dict().items()
    pf_histogram_data = list(map(list, pf_histogram_data))
    pf_histogram_data.insert(0, [_('Forte class'), _('Number of pedal settings')])

    # interval vector
    iv_string_list = [str(i) for i in range(1, 7)]
    iv_columns = COLUMNS[:]
    iv_columns.extend(iv_string_list)

    # global interval_vector
    iv_sum_series = df[iv_string_list].sum()
    iv_sum_distribution_series = (iv_sum_series - iv_sum_series.mean()) / iv_sum_series.std()
    iv_sum_distribution_series = iv_sum_distribution_series.to_dict().items()
    iv_sum_distribution_series = list(map(list, sorted(iv_sum_distribution_series)))
    iv_sum_distribution_series.insert(0, [_('Interval'), _('Amount')])

    args = {
        'type_table_data': type_count_df,
        'chord_type_pie_data': chord_type_pie_data,
        'pf_histogram_data': pf_histogram_data,
        'interval_vector_data': iv_sum_series,
        'interval_vector_line_data': iv_sum_distribution_series,
    }

    return render(request, 'statistics.html', args)

pedal_settings/templates/_accident_button.html
    <div class="controls">
        {{ item.errors }}
        <label>{{ item.name | title }}</label>
        {% for choice in item.field.choices %}
            <div class="radio">
                <input name='{{ item.name }}'
                    id='{{ item.auto_id }}_{{ forloop.counter0 }}' type='radio' value='{{ choice.0 }}'
                    {% if not form.is_bound %}
                        {% ifequal item.field.initial choice.0 %} checked='checked' {% endifequal %}
                        {% else %}{% ifequal item.data choice.0 %} checked='checked' {% endifequal %}
                    {% endif %}/>
                <label for='{{ item.auto_id }}_{{ forloop.counter0 }}'>{{ choice.1 }}</label>
            </div>
        {% endfor %}
    </div>

pedal_settings/templates/_top_nav.html
{% load i18n %}
<li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
<li><a href="{% url "dashboard" %}">{% trans "Dashboard" %}</a></li>
<li><a href="{% url "about" %}">{% trans "About" %}</a></li>

pedal_settings/templates/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load i18n %}
    <title>{% trans "Harp | " %}{% block title %}{% endblock %}</title>
    {% load staticfiles %}

    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet">
    <link href="{% static "css/jquery.dataTables.css" %}" rel="stylesheet">
    {% block style %}
    {% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-25220567-1', 'auto');
  ga('send', 'pageview');
    </script>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href='{% url "dashboard" %}'>{% trans "Harp" %}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              {% include "_top_nav.html" %}
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
        <div class="starter-template">
            <h1>{% trans "About" %}</h1>
            <p class="lead">
                {% blocktrans %}
                This Webapp is part of a broader combinatorial and statistic study about the orchestral harp pedals,
                developed by Ricardo Bordini, Jamary Oliveira and Marcos da Silva Sampaio.
                {% endblocktrans %}
            </p>
                <p class="lead">{% trans "This page is under" %} <a href="{% static "LICENSE.txt" %}">{% trans "MIT license" %}</a>, 2015.</p>
        </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    {% block javascript %}
    {% endblock %}

  </body>
</html>

pedal_settings/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load i18n %}
    <title>{% trans "Harp | " %}{% block title %}{% endblock %}</title>
    {% load staticfiles %}

    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet">
    <link href="{% static "css/jquery.dataTables.css" %}" rel="stylesheet">
    {% block style %}
    {% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-25220567-1', 'auto');
  ga('send', 'pageview');
    </script>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href='{% url "home" %}'>{% trans "Harp" %}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              {% include "_top_nav.html"%}
          </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li id="all_settings"><a href="{% url "show_all_settings" %}">{% trans "All settings" %}</a></li>
            <li id="get_by_index"><a href="{% url "get_by_index" %}">{% trans "Get by index" %}</a></li>
            <li id="get_by_prime"><a href="{% url "get_by_prime" %}">{% trans "Get by prime form" %}</a></li>
            <li id="get_by_accidents"><a href="{% url "get_by_accidents" %}">{% trans "Get by accidents" %}</a></li>
            <li id="download_all_settings"><a href="{% url "download_all_settings" %}">{% trans "Get TXT file" %}</a></li>
            <li id="show_statistics"><a href="{% url "show_statistics" %}">{% trans "Statistics" %}</a></li>
          </ul>
        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          {% block body %}

          {% endblock %}
        </div>
      </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    {% block javascript %}
    {% endblock %}

  </body>
</html>

pedal_settings/templates/dashboard.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}
    {% trans "Home" %}
{% endblock %}

{% block body %}
    <h1>{% trans "Dashboard" %}</h1>
    <hr>
        <h2>{% trans "Pedal settings" %}</h2>
        <p>{% blocktrans %}
            The orchestral harp has 7 pedals, one for each pitch class. Each pedal has three possible positions: flat, natural or sharp.
            We call each permutation of these 7 pedals in the three positions <b>pedal settings</b>.
            There are 2187 possible pedal settings in the harp. We create a harp pedal settings index in a base 3 numeric system:
            0, 1, 2, 10, 11, 12, 20, 21, 22, 100, 101, 102, etc.
        {% endblocktrans %}</p>

        <h2>{% trans "Queries" %}</h2>
        <p>{% blocktrans %}
            This app provides a full list with all pedal 2187 settings, a table to download, and four ways to query pedal settings:
        {% endblocktrans %}</p>
        <ul>
            <li>{% trans "by index" %}</li>
            <li>{% trans "by the resulting pitch set class prime form" %}</li>
            <li>{% trans "by the pitch accidents" %}</li>
        </ul>
        <p>{% trans "These queries are available in the sidebar." %}</p>

        <h2>{% trans "Statistics" %}</h2>
        <p>{% blocktrans %}
            There are some statistics available, with sonority central tendency, chord type distribution, etc.
        {% endblocktrans %}</p>


{% endblock %}

pedal_settings/templates/filter_accidents.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Get by accidents" %}
{% endblock %}

{% block body %}
<h1>{% trans "Get by accidents" %}</h1>
<hr>

<p>{% trans "Set the pedals settings:" %}</p>
<form class="form-inline" action="{% url 'get_by_accidents' %}" method="post">
    {% csrf_token %}
    {% for pedal in form %}
        {% include "_accident_button.html" with item=pedal %}
    {% endfor %}
    <input class="btn btn-default" type="submit" value={% trans "Submit" %} />
</form>

{% endblock %}

pedal_settings/templates/filter_index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Get by index" %}
{% endblock %}

{% block body %}
<h1>{% trans "Get by index" %}</h1>
<hr>

<form action="{% url 'get_by_index' %}" method="post">
    {% csrf_token %}
     <div class="col-lg-6">
        <div class="input-group">
            <input id="id_settings_index" maxlength="7" name="settings_index" type="text"
                   class="form-control" placeholder="{% trans "Insert an index number in base 3 between 0 and 2222222..." %}">
            <span class="input-group-btn">
                <input class="btn btn-default" type="submit" value={% trans "Submit" %} />
            </span>
        </div>
     </div>
</form>

{% endblock %}

pedal_settings/templates/filter_prime_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Get by prime form" %}
{% endblock %}

{% block body %}
<h1>{% trans "Get by prime form" %}</h1>
<hr>

<form action="{% url 'get_by_prime' %}" method="post">
    {% csrf_token %}
     <div class="col-lg-6">
        <div class="input-group">
            <input id="id_settings_prime" minlength="4" maxlength="7" name="settings_prime" type="text"
                   class="form-control" placeholder="{% trans "Insert a pcset prime form such as 02468A..." %}">
            <span class="input-group-btn">
                <input class="btn btn-default" type="submit" value={% trans "Submit" %} />
            </span>
        </div>
     </div>
</form>

{% endblock %}

pedal_settings/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load i18n %}
    <title>{% trans "Harp | " %}{% block title %}{% endblock %}</title>
    {% load staticfiles %}

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/cover.css" %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{% static "js/ie8-responsive-file-warning.js" %}"></script><![endif]-->
    <script src="{% static "js/ie-emulation-modes-warning.js" %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Harp</h3>
              <nav>
                <ul class="nav masthead-nav">
                    {% include "_top_nav.html" %}
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Harp Pedals App.</h1>
            <p class="lead">{% blocktrans %}
                Harp Pedals is an application that returns the Harp's pedals settings and statistics.
                {% endblocktrans %}</p>
            <p class="lead">
              <a href="{% url "dashboard" %}" class="btn btn-lg btn-default">{% trans "Enter" %}</a>
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>{% trans "Developed by" %} <a href="http://marcos.sampaio.me" target="_blank">Marcos da Silva Sampaio</a>
    {% trans "and" %} <a href="http://musica.ufma.br/bordini/" target="_blank">Ricardo Mazzini Bordini</a>..</p>
            </div>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/docs.min.js" %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
  </body>
</html>

pedal_settings/templates/show_settings.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load dispositions_extras %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<h1>{% trans "All pedal settings" %}</h1>
<hr>

    {% if settings %}
    <p>{{ settings }} {% trans "pedals settings" %}</p>
    {% endif %}
          <div class="table-responsive">
            <table id="pedals_table" class="display" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th>{% trans "Index" %}</th>
                    <th>{% trans "Notes (scalar)" %}</th>
                    <th>{% trans "Notes (radial)" %}</th>
                    <th>{% trans "PC Set" %}</th>
                    <th>{% trans "Prime Form" %}</th>
                    <th>{% trans "Forte Class" %}</th>
                    <th>{% trans "Pedals Settings" %}</th>
                    <th>{% trans "MIDI file" %}</th>
                </tr>
                </thead>
                <tbody>
                {% for index, row in df.iterrows %}
                <tr>
                    {% if radial %}
                    <td>{{ index|radial_format }}</td>
                    {% else %}
                    <td>{{ index|scalar_format }}</td>
                    {% endif %}
                    <td>{% dict_get row 'Notes (scalar)' %}</td>
                    <td>{% dict_get row 'Notes (radial)' %}</td>
                    <td>{% dict_get row 'PC Set' %}</td>
                    <td>{% dict_get row 'Prime Form' %}</td>
                    <td>{% dict_get row 'Forte class' %}</td>
                    <td>
                        <svg width="80" height="24">
                            <line x1="0" y1="12" x2="80" y2="12" style="stroke:rgb(0,0,0);stroke-width:1"/>
                            <line x1="35" y1="0" x2="35" y2="24" style="stroke:rgb(0,0,0);stroke-width:1"/>

                            <rect x="5" y="{% get_accident row.Accidents 'd' 7 %}" width="4" height="10" />
                            <rect x="15" y="{% get_accident row.Accidents 'c' 7 %}" width="4" height="10" />
                            <rect x="25" y="{% get_accident row.Accidents 'b' 7 %}" width="4" height="10" />

                            <rect x="40" y="{% get_accident row.Accidents 'e' 7 %}" width="4" height="10" />
                            <rect x="50" y="{% get_accident row.Accidents 'f' 7 %}" width="4" height="10" />
                            <rect x="60" y="{% get_accident row.Accidents 'g' 7 %}" width="4" height="10" />
                            <rect x="70" y="{% get_accident row.Accidents 'a' 7 %}" width="4" height="10" />
                        </svg>
                    </td>
                    <td><a href="{{ STATIC_URL }}midi/{{ index }}.mid">{{ index }}.mid</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
{% endblock %}

{% block javascript %}
    <script src="{% static "js/jquery.dataTables.min.js" %}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#pedals_table').DataTable({
                "language": {
                    "url": "{{ language_url }}"
                }
            });
        } );
</script>
{% endblock %}